// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMbuZkeaFHTh2ukHzOXZfOasEozUAHMeg',
    appId: '1:988713608420:web:813bf298cb4f9f90d2b8f1',
    messagingSenderId: '988713608420',
    projectId: 'foodordering1',
    authDomain: 'foodordering1.firebaseapp.com',
    storageBucket: 'foodordering1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmdGOCE6jVIIT5gAc-cJVrjJcCb46k4gI',
    appId: '1:988713608420:android:aa3f8a77a2a0ccbbd2b8f1',
    messagingSenderId: '988713608420',
    projectId: 'foodordering1',
    storageBucket: 'foodordering1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqlzCZn8u62Na1LB8oFXRsN-D9koOejZY',
    appId: '1:988713608420:ios:e3b30832441a7adad2b8f1',
    messagingSenderId: '988713608420',
    projectId: 'foodordering1',
    storageBucket: 'foodordering1.firebasestorage.app',
    iosBundleId: 'com.example.firebasestorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqlzCZn8u62Na1LB8oFXRsN-D9koOejZY',
    appId: '1:988713608420:ios:e3b30832441a7adad2b8f1',
    messagingSenderId: '988713608420',
    projectId: 'foodordering1',
    storageBucket: 'foodordering1.firebasestorage.app',
    iosBundleId: 'com.example.firebasestorage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMbuZkeaFHTh2ukHzOXZfOasEozUAHMeg',
    appId: '1:988713608420:web:a5622f409a32bfc8d2b8f1',
    messagingSenderId: '988713608420',
    projectId: 'foodordering1',
    authDomain: 'foodordering1.firebaseapp.com',
    storageBucket: 'foodordering1.firebasestorage.app',
  );
}
